DELIMITER $$

CREATE FUNCTION `FN_CHECK_QUANTITY`(I_QUANTITY INT) RETURNS TEXT CHARSET latin1
BEGIN
    DECLARE  O_RESULT TEXT;
	IF (I_QUANTITY>=0 AND I_QUANTITY IS NOT NULL) THEN 
	SET O_RESULT='TRUE';
	ELSE SET O_RESULT='ENTER A  NUMBER GREATER THAN 0 IN QUANTITY';
	END IF;
	RETURN O_RESULT;
    END$$

DELIMITER ;