DELIMITER $$

CREATE PROCEDURE `PR_PLACE_ORDER`(IN I_NEXT_ITEM_VALUE TEXT,IN I_NEXT_QUANTITY_VALUE INT
,IN I_SEATNO INT,OUT O_MESSAGE TEXT)
BEGIN
    DECLARE L_PRICE INT;
  SELECT PRICE INTO L_PRICE FROM FOOD_ITEMS WHERE ITEM_NAME=I_NEXT_ITEM_VALUE;
  SELECT ITEM_ID,TOTAL_QTY_PRODUCED INTO @S_ITEMID,@S_TOTAL_QTY FROM FOOD_SCHEDULE WHERE ITEM_ID IN 
 (SELECT ID FROM FOOD_ITEMS WHERE ITEM_NAME=I_NEXT_ITEM_VALUE) AND SESSION_ID IN (
 SELECT ID  FROM TIME_SCHEDULE WHERE START_TIME<=CURRENT_TIME AND END_TIME>=CURRENT_TIME);
 SELECT IFNULL(SUM(QUANTITY),0) INTO @USED_ITEMS FROM ORDER_DETAILS WHERE ITEM_ID=@S_ITEMID AND DATE(TIME_OF_ORDER)=CURDATE();
 /*IF (@USED_ITEMS IS NULL) THEN 
  SET @USED_ITEMS=0;
  #SELECT CONCAT("USED ITEMS",@USED_ITEMS);
  END IF;*/
   IF (@S_TOTAL_QTY >= @USED_ITEMS+I_NEXT_QUANTITY_VALUE)THEN
    /*SELECT MAX(ID) INTO @LAST_ROW FROM ORDERDETAILS;      
    UPDATE HOTEL_SEATS SET STATUS=1 WHERE SEAT_NO=I_SEATNO; */
    INSERT INTO ORDER_DETAILS(ORDER_NO,ITEM_ID,QUANTITY,PRICE,SEAT_ID) VALUES(@ORDER_ID,@S_ITEMID,I_NEXT_QUANTITY_VALUE,I_NEXT_QUANTITY_VALUE*L_PRICE,I_SEATNO);
  SET O_MESSAGE='YOUR ORDER HAS BEEN PLACED';
    #UPDATE HOTEL_SEATS SET STATUS=0 WHERE SEAT_NO=I_SEATNO;
    
    ELSE SET O_MESSAGE='INSUFFICIENT ITEMS';
    END IF;
  
    END$$

DELIMITER ;